// GDS Graph Projections for Personal Knowledge
// Generated by create-context-graph
// Note: Requires Neo4j GDS plugin (AuraDS or Enterprise + GDS)

// Full entity projection (all node labels and relationship types)
CALL gds.graph.project(
  'personal_knowledge_full',
  ['Person', 'Organization', 'Location', 'Event', 'Object', 'Note', 'Contact', 'Project', 'Topic', 'Bookmark', 'JournalEntry'],
  ['WORKS_FOR', 'LOCATED_AT', 'PARTICIPATED_IN', 'KNOWS', 'TAGGED', 'WORKED_ON', 'REFERENCES', 'RELATED_TO', 'MENTIONED_IN', 'BELONGS_TO', 'INSPIRED_BY']
);

// Community detection
CALL gds.louvain.write('personal_knowledge_full', {
  writeProperty: 'community'
});

// PageRank centrality
CALL gds.pageRank.write('personal_knowledge_full', {
  writeProperty: 'pagerank'
});

// FastRP embeddings for structural similarity
CALL gds.fastRP.write('personal_knowledge_full', {
  embeddingDimension: 128,
  writeProperty: 'fastrp_embedding'
});

// Clean up projection
CALL gds.graph.drop('personal_knowledge_full');
