#!/usr/bin/env node
/**
 * graph-census.cjs — refresh the live census block in docs/KNOWLEDGE-GRAPH.md.
 *
 * Read-only against Neo4j. Reads Bolt creds from the repo-root .env
 * (server-side, never printed). Rewrites the doc section between
 * <!-- CENSUS:START --> and <!-- CENSUS:END -->.
 *
 * Usage: node frontend/scripts/graph-census.cjs
 */
const fs = require("fs");
const path = require("path");

const REPO = path.resolve(__dirname, "..", "..");
const DOC = path.join(REPO, "docs", "KNOWLEDGE-GRAPH.md");
const START = "<!-- CENSUS:START -->";
const END = "<!-- CENSUS:END -->";

function loadEnv(p) {
  const env = {};
  for (const line of fs.readFileSync(p, "utf8").split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const i = t.indexOf("=");
    if (i > 0) env[t.slice(0, i)] = t.slice(i + 1);
  }
  return env;
}

async function main() {
  const env = loadEnv(path.join(REPO, ".env"));
  const neo4j = require(path.join(REPO, "frontend", "node_modules", "neo4j-driver"));
  const driver = neo4j.driver(
    env.NEO4J_URI,
    neo4j.auth.basic(env.NEO4J_USERNAME, env.NEO4J_PASSWORD),
    { disableLosslessIntegers: true }
  );
  const session = driver.session({ defaultAccessMode: neo4j.session.READ });
  const q = async (cyp) => (await session.run(cyp)).records.map((r) => r.toObject());

  try {
    const totalNodes = (await q("MATCH (n) RETURN count(n) AS c"))[0].c;
    const totalRels = (await q("MATCH ()-[r]->() RETURN count(r) AS c"))[0].c;
    const baseline = await q(
      `MATCH (n) WHERE NOT n:ProjectionNode
       RETURN labels(n) AS labs, count(*) AS c ORDER BY c DESC LIMIT 15`);
    const projections = await q(
      `MATCH (n:ProjectionNode)
       RETURN n._projection AS src, count(*) AS c ORDER BY c DESC`);
    const semBreakdown = await q(
      `MATCH (s:SemanticEntity)
       RETURN [l IN labels(s) WHERE l <> 'SemanticEntity'][0] AS kind, count(*) AS c
       ORDER BY c DESC`);
    const semEdges = await q(
      `MATCH (a:SemanticEntity)-[r]->(b)
       RETURN type(r) AS t, count(*) AS c ORDER BY c DESC`);

    const now = new Date().toISOString().slice(0, 16).replace("T", " ") + " UTC";
    const L = [];
    L.push(`_Last census: ${now} — regenerated by \`node frontend/scripts/graph-census.cjs\`.`);
    L.push(`Do not hand-edit between the markers._`);
    L.push(``);
    L.push(`**${totalNodes.toLocaleString()} nodes · ${totalRels.toLocaleString()} relationships**`);
    L.push(``);
    L.push(`| Layer | Nodes |`);
    L.push(`|---|---|`);
    for (const b of baseline) {
      const label = b.labs.filter((l) => l !== "SemanticEntity").join("+") || "SemanticEntity";
      const extra = b.labs.includes("SemanticEntity") ? ` (semantic: ${label})` : "";
      L.push(`| baseline \`${b.labs.join(":")}\`${extra} | ${b.c.toLocaleString()} |`);
    }
    for (const p of projections) {
      L.push(`| projection \`${p.src}\` | ${p.c.toLocaleString()} |`);
    }
    L.push(``);
    L.push(`Semantic pilot breakdown: ` +
      semBreakdown.map((s) => `${s.kind} ${s.c}`).join(" · "));
    L.push(``);
    L.push(`Semantic edges: ` +
      semEdges.map((e) => `${e.t} ${e.c}`).join(" · "));
    const block = L.join("\n");

    let doc = fs.readFileSync(DOC, "utf8");
    const si = doc.indexOf(START), ei = doc.indexOf(END);
    if (si < 0 || ei < 0 || ei < si) throw new Error("census markers not found in doc");
    doc = doc.slice(0, si + START.length) + "\n" + block + "\n" + doc.slice(ei);
    fs.writeFileSync(DOC, doc);
    console.log(`census updated (${now}): ${totalNodes} nodes, ${totalRels} rels`);
  } finally {
    await session.close();
    await driver.close();
  }
}

main().catch((e) => { console.error("census failed:", e.message); process.exit(1); });
