/**
 * Domain configuration for Personal Knowledge
 * Generated by create-context-graph
 */

export const DOMAIN = {
  id: "personal-knowledge",
  name: "Personal Knowledge",
  description: "Personal note-taking, contact management, project tracking, and knowledge connections",
  tagline: "AI-powered Personal Knowledge Graph",
};

export const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api";

export const NODE_COLORS: Record<string, string> = {"Bookmark": "#d946ef", "Contact": "#0891b2", "Event": "#f97316", "JournalEntry": "#ec4899", "Location": "#a855f7", "Note": "#fbbf24", "Object": "#eab308", "Organization": "#64748b", "Person": "#22c55e", "Project": "#8b5cf6", "Topic": "#10b981"};

export const NODE_SIZES: Record<string, number> = {"Bookmark": 15, "Contact": 25, "Event": 20, "JournalEntry": 20, "Location": 20, "Note": 20, "Object": 20, "Organization": 20, "Person": 20, "Project": 25, "Topic": 20};

export const DEFAULT_CYPHER = `MATCH (n:Note)-[r]-(t) RETURN n, r, t LIMIT 100`;

export const SCHEMA_NODE_SIZE = 30;
export const SCHEMA_REL_COLOR = "#94a3b8";

export interface GraphData {
  results: Record<string, unknown>[];
}

export interface DemoScenario {
  name: string;
  prompts: string[];
}

export const DEMO_SCENARIOS: DemoScenario[] = [{"name": "Knowledge Exploration", "prompts": ["What notes have I written about machine learning this month?", "Show me all topics connected to my graph databases research", "Find bookmarks I saved but haven\u0027t read yet about distributed systems"]}, {"name": "People \u0026 Projects", "prompts": ["Which contacts have I not been in touch with for over 3 months?", "Show me all notes and updates related to my side project", "Who do I know that works in the AI space?"]}, {"name": "Reflection \u0026 Patterns", "prompts": ["What topics appear most frequently in my journal entries?", "Show me the connections between my reading and my projects", "What were my most productive weeks and what was I working on?"]}];
